<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>TicketSystem.Api-2ef76daa-006d-4e38-90ce-4c255c927378</UserSecretsId>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TicketSystem.Application\TicketSystem.Application.csproj" />
    <ProjectReference Include="..\TicketSystem.Infrastructure\TicketSystem.Infrastructure.csproj" />
    <ProjectReference Include="..\TicketSystem.Domain\TicketSystem.Domain.csproj" />
  </ItemGroup>

</Project>
